config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users, only: [:new, :create]
  resources :gifs, only: [:index]
  resources :favorites, only: [:new, :create, :index, :show, :destroy]

  namespace :admin do
    resources :categories, only: [:index, :new, :show, :create, :destroy] do
      resources :gifs, only: [:new, :create, :destroy]
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :gifs
  validates :name, presence: true,
                   uniqueness: true,
                   format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows one word"}

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  validates :sha, uniqueness: true
  
  belongs_to :gif
  belongs_to :user
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :category
  has_many :favorites
end

app/models/giphy_gifs.rb
require 'faraday'

class GiphyGifs
  def initialize(category_name)
    api = Faraday.get("http://api.giphy.com/v1/gifs/search?q=#{category_name}&api_key=dc6zaTOxFJmzC&limit=80")
    raw_data = api.body
    @gif_data = JSON.parse(raw_data)
  end

  def gif_urls
    gifs = @gif_data["data"]
    urls = gifs.map do |gif|
      gif["images"]["fixed_width"]["url"]
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :favorites
  has_many :gifs, through: :favorites
  has_many :categories, through: :gifs

  enum role: %w(default admin)

  validates :username, presence: true, uniqueness: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_user.admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:create] = "Category successfully created."
      redirect_to new_admin_category_gif_path(@category.id)
    else
      flash[:error] = "Please try again."
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    category = Category.find(params[:id]).destroy
    flash[:logout] = "The category '#{category.name}' has been deleted."
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/gifs_controller.rb
class Admin::GifsController < Admin::BaseController
  def new
    @category = Category.last
    @gifs = Gif.new
    @potential_gifs = GiphyGifs.new(Category.find(params[:category_id]).name).gif_urls
  end

  def create
    save_gifs(get_urls)
    flash[:create] = "New gifs have been added."
    redirect_to admin_category_path(params[:category_id])
  end

  private

  def get_urls
    urls = []
    1.upto(40) do |num|
      urls << params["#{num}"]
    end
    urls.compact
  end

  def save_gifs(urls)
    urls.each do |url|
      Gif.create(image_path: url, category_id: params[:category_id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :require_admin
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # def require_admin
  #   render file: '/public/404' unless current_user.admin?
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def new
    @favorites = Favorite.new
    @categories = Category.all
  end

  def create
    create_favorites
    redirect_to favorites_path
    flash[:create] = "Your favorites have been added."
  end

  def index
    @favorites = Favorite.all
  end

  def destroy
    Favorite.find(params[:id]).destroy
    flash[:error] = "Your favorite has been removed."
    redirect_to favorites_path
  end

  private

  def create_favorites
    favorited_urls = get_favorited_urls
    favorited_gifs = get_favorited_gifs(favorited_urls)
    favorited_gifs.each do |gif|
      sha = Digest::SHA1.hexdigest("#{gif.image_path}#{current_user.username}")
      Favorite.create(gif_id: gif.id, user_id: current_user.id, sha: sha)
    end
  end

  def get_favorited_urls
    categories    = Category.all
    favorite_gifs = []
    categories.each do |category|
      1.upto(category.gifs.count) do |num|
        favorite_gifs << params["#{category.name}#{num}"]
      end
    end
    favorite_gifs.compact
  end

  def get_favorited_gifs(favorited_urls)
    favorited_urls.map do |url|
      Gif.find_by(image_path: url)
    end
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  def index
    @categories = Category.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      flash[:login] = "Welcome, you are logged in."
      session[:user_id] = @user.id


      if @user.admin?
        flash[:login] = "Welcome, you are logged in as an admin."
        redirect_to admin_categories_path
      else
        redirect_to gifs_path
      end
    else
      flash.now[:error] = "Invalid. Please try again."
      render 'sessions/new'
    end
  end

  def destroy
    session.clear
    flash[:logout] = "You have been logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:create] = "Success! Your account has been created."
      redirect_to gifs_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h2>All Categories</h2>

<h3><%= link_to "New Category", new_admin_category_path %></h3>


<% @categories.each do |category| %>
  <p><%= link_to category.name, admin_category_path(category.id) %>
    <div class="remove-link">
    <%= link_to "Delete", admin_category_path(category.id), method: :delete %>
  </div>
  </p>
<% end %>

app/views/admin/categories/new.html.erb
<h1>Your New Category</h1>

<%= form_for [:admin, @category] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Search"%>
<% end %>

app/views/admin/categories/show.html.erb
<h2>Category: '<%= @category.name %>'</h2>

<h3><%= link_to "All Categories", admin_categories_path %></h3>


<% @category.gifs.each_with_index do |gif, index|  %>
  <img src="<%= gif.image_path %>">
  <% if (index + 1)%5 == 0 %><br><% end %>
<% end %>

app/views/admin/gifs/new.html.erb
<h2>Search result for: '<%= @category.name %>' </h2>

<%= form_for(@gifs, url: admin_category_gifs_path) do |f| %>
  <p><%= f.submit "Generate Gifs" %></p>
  <% @potential_gifs.each_with_index do |gif_url, index| %>
    <input type="checkbox" name="<%= index + 1 %>" value="<%= gif_url %>">
    <img src="<%= gif_url %>">
    <% if (index + 1)%4 == 0 %><br><% end %>
  <% end %>
<% end %>

app/views/favorites/index.html.erb
<h2>Favorited Gifs</h2>

<% current_user.categories.each do |category| %>
  <h3><%= category.name %></h3>
  <% current_user.gifs.each.with_index do |gif, index| %>
    <% if gif.category.name == category.name %>
    <div class="index-images">
      <img src="<%= gif.image_path %>">
      <div class="remove-link">
        <%= link_to "Unfavorite Gif", favorite_path(Favorite.find_by(user_id: current_user.id, gif_id: gif.id).id), method: :delete, id: "#{index+1}-delete" %>
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/favorites/new.html.erb
<h2>Favorite Your Gifs</h2>

<%= form_for @favorites do |f| %>
  <% @categories.each do |category| %>
  <%= f.submit "Favorite Gifs" %>
    <h3><%= category.name %></h3>
    <% category.gifs.each.with_index do |gif, index| %>
        <input type="checkbox" name="<%= "#{category.name}#{index + 1}" %>" value="<%= gif.image_path %>">
        <img src="<%= gif.image_path %>">
        <% if (index + 1)%4 == 0 %><br><% end %>
    <% end %>
  <% end %>
<% end %>

app/views/gifs/index.html.erb
<h2>All Gifs</h2>

<h3> <%= link_to "Favorite Your Gifs", new_favorite_path %> </h3>

<% @categories.each do |category| %>
  <h3><%= category.name %></h3>
  <% category.gifs.each do |gif| %>
    <img src="<%= gif.image_path %>">
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifGenerator</title>
  <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville|Montserrat:700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="wrapper">
      <h1>Gif Generator</h1>
    </div>
  </header>

  <nav>
    <div class="wrapper">

      <% if current_user %>
      <p>Hello, <%= current_user.username %>!</p>
      <p> <%= link_to "Logout", logout_path, method: :delete %></p>
      <% else %>
      <p><%= link_to "New User", new_user_path %></p>
      <% end %>
    </div>

  </nav>

    <% flash.each do |type, message| %>
    <div class="<%= "flash-#{type}" %> flash" >
    <%= content_tag :div, message, class: "wrapper" %>
    </div>
    <% end %>

  <main class="wrapper">


    <%= yield %>

  </main>
</body>
</html>

app/views/users/new.html.erb
<h2>New User Registration</h2>

<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Create Account" %>

<% end %>